# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  custom:
    to-develop:
      - step:
          caches:
            - node
          script:
            - ssh bitbucket@{server_ip} ' echo "DEVELOP start pipeline!"'

    to-production:
      - step:
          script:
            - ssh bitbucket@{server_ip} ' echo "PRODUCTION start pipeline!"'
